WINDOW_TITLE = "Sudoku Solver"
MAIN_WINDOW_X = 100
MAIN_WINDOW_Y = 100
MAIN_WINDOW_WIDTH = 500
MAIN_WINDOW_HEIGHT = 500

# style sheet hints
CELL_BORDER_WIDTH = 0.5
CELL_BORDER_SIDE_WIDTH = 2
CELL_BORDER_STYLE = "solid"
CELL_BORDER_COLOR = "black"
CELL_BORDER_RADIUS = 4
CELL_BACKGROUND_COLOR = "white"
CELL_SELECTION_BACKGROUND_COLOR = "orange"
CELL_FONT_COLOR = "red"
CELL_FONT_SIZE = 40
CELL_OUTLINE_COLOR = "yellow"            # outline doesn't appear to do anything
CELL_OUTLINE_RADIUS = 2
CELL_OUTLINE_STYLE = "none"
CELL_PADDING = 0
CELL_MARGIN = 0

CELL_FOCUS_BORDER_WIDTH = 0.5
CELL_FOCUS_BORDER_SIDE_WIDTH = 2
CELL_FOCUS_BORDER_STYLE = "solid"
CELL_FOCUS_BORDER_COLOR = "black"
CELL_FOCUS_BORDER_RADIUS = 4
CELL_FOCUS_BACKGROUND_COLOR = "#dcdcdc"
CELL_FOCUS_SELECTION_BACKGROUND_COLOR = "orange"
CELL_FOCUS_FONT_COLOR = "red"
CELL_FOCUS_FONT_SIZE = 40
CELL_FOCUS_OUTLINE_COLOR = "yellow"      # outline doesn't appear to do anything
CELL_FOCUS_OUTLINE_RADIUS = 2
CELL_FOCUS_OUTLINE_STYLE = "none"
CELL_FOCUS_PADDING = 0
CELL_FOCUS_MARGIN = 0
