from PySide6.QtCore import Qt

WINDOW_TITLE = "Sudoku Solver"
GRID_SIZE = 9
MAIN_WINDOW_X = 100
MAIN_WINDOW_Y = 100
MAIN_WINDOW_WIDTH = 500
MAIN_WINDOW_HEIGHT = 500

SCROLL_MODE = "v wrap" # "wrap/no wrap"

BORDER_THICK_COLOR = "black"
#BORDER_THIN_COLOR = "blue"
BORDER_THIN_COLOR = "lightgray"
BORDER_THIN_STYLE = Qt.PenStyle.DotLine
BORDER_THICK_STYLE = Qt.PenStyle.SolidLine

CELL_EDIT_BACKGROUND_COLOR = "white"
CELL_EDIT_FONT_COLOR = "blue"
CELL_EDIT_BORDER_SIZE = "none"
CELL_EDIT_PADDING_SIZE = 0
